### ISSUE TITLE
work without navbar-inverse

### ISSUE THREAD

**Issue by newschapmj1** [BlackrockDigital/startbootstrap-logo-nav#2]
Thanks for building this theme.

When I remove navbar-inverse (line 33) the menu works as expected when the screen is above 767px.
However, below this the hamburger  and linked menus are not visible.

Is there a simple way around this?

**Comment by davidtmiller** [comment]
I will check the code. It should be working with any .navbar-fixed-top class. I may change this and make a custom navbar class for the logo nav.
